In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import itertools as it
import scipy as scp
import pandas as pd
import copy as cp
from tqdm import tqdm 

sns.set_theme(style="darkgrid",context='talk', font_scale=1.1)
%matplotlib inline

import numpy as np
from copy import deepcopy

In [35]:
n = np.array([[100], [100]])

In [36]:
p12 = 0.01
p21 = 0.01

U = np.matrix([[1, -p12],
               [-p21, 1]])

In [37]:
n_list = []
for i in range(10):
    n_list.append(n)
    n = np.array(np.matmul(U, n))

In [38]:
n_list

[array([[100],
        [100]]),
 array([[99.],
        [99.]]),
 array([[98.01],
        [98.01]]),
 array([[97.0299],
        [97.0299]]),
 array([[96.059601],
        [96.059601]]),
 array([[95.09900499],
        [95.09900499]]),
 array([[94.14801494],
        [94.14801494]]),
 array([[93.20653479],
        [93.20653479]]),
 array([[92.27446944],
        [92.27446944]]),
 array([[91.35172475],
        [91.35172475]])]